[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 1m

lib_deps =
    adafruit/Adafruit NeoPixel@^1.15.2
    https://github.com/jhpinder/piper-midi.git